code/urls.py
from django.conf.urls.defaults import *
from django.contrib.comments.models import FreeComment

urlpatterns = patterns('',
	(r'^music/', 		include('zoid.music.urls')),
	(r'^blogs/',		include('zoid.blogs.urls')),
	(r'^feeds/',		include('zoid.feeds.urls')),
	(r'^prefs/',		include('zoid.prefs.urls')),
    (r'^admin/', 		include('django.contrib.admin.urls')),	
	(r'^comments/', 	include('django.contrib.comments.urls.comments')),
	(r'^$', 			'zoid.music.views.default_index'),
)

code/music/models.py
"""
	music.models
	Defines classes directly related to tracks, and the parsing of them,
	especially artist metadata and track metadata (including popularity).
"""

from django.db import models
from django.contrib.auth.models import User
from zoid.helpers.utils import get_data_from_url
#from zoid.statistics.models import TrackStatistics

class ArtistManager(models.Manager):
	"""Manages overarching responsibilites for the artist class."""
	
	def find_or_create(self, artist_name):
		"""Finds or creates and returns an artist object given its name.
		Case insensitive."""
		artist = Artist.objects.filter(name__iexact=artist_name)
		if artist: return artist[0]
		artist = Artist(name=artist_name)
		artist.save()
		return artist

class Artist(models.Model):
	"""An artist identifier, eg. 'MSTRKRFT'"""
	name = models.CharField(max_length=200)
	description = models.TextField(blank=True, null=True)
	
	objects = models.Manager()
	artist_manager = ArtistManager()
	
	def __unicode__(self): return self.name
		
		
	class Admin: 
		pass

class TrackManager(models.Manager):
	"""Manages track related things."""
	
	def find_or_create(self, artist, title):
		"""This looks especially nasty, thanks to alot of bug fixing.
		Due for a cleanup."""
		if artist and title:
			artistobj = Artist.artist_manager.find_or_create(artist)
			track = self.find_by_artist_model_and_title(artistobj, title)
		else: track = None
		if not track:
			if artist:
				artistobj = Artist.artist_manager.find_or_create(artist)
				track = Track(artist=artistobj, title=title)
			else:
				track = Track(title=title)
			track.save()
			#TrackStatistics.manager.create_from_track(track)
		return track

	def find_by_artist_model_and_title(self, artist, title):
		track = Track.objects.filter(artist=artist).filter(title__iexact=title)
		if track: return track[0]
		
	def find_by_artist_and_title(self, artist, title):
		track = Track.objects.filter(artist__name__iexact=artist).filter(title__iexact=title)
		if track: return track[0]

class Track(models.Model):
	"""A track identifier, i.e. 'MSTRKRFT - The Looks'"""
	artist = models.ForeignKey(Artist, null=True, blank=True)
	title = models.CharField(max_length=300)
	slug = models.SlugField(prepopulate_from=("artist","title"))
	
	user_for_relation = None
	
	objects = models.Manager()
	track_manager = TrackManager()
	
	def set_user_for_relation(self,user):
		self.user_for_relation = user
	
	def user_relation(self):
		return Popularity.popper.state(self.user_for_relation, self)

	def __unicode__(self):
		return '%(artist)s - %(title)s' % \
		{'artist': self.artist, 'title': self.title}
		
	class Meta:
		unique_together = (("artist", "title"),)
	# Admin stuff	
	class Admin:
		pass


class PopularityManager(models.Manager):
	"""Manages track popularity, i.e. if a user loves or hates a track."""
	def love(self, user, track):
		"""Makes user love track."""
		trackpop = self.__get(user, track)
		if trackpop:
			trackpop.love()
			trackpop.save()
			return sum([t.score for t in Popularity.objects.filter(track=track)])

	def hate(self, user, track):
		"""Makes user hate track."""
		trackpop = self.__get(user, track)
		if trackpop:
			trackpop.hate()
			trackpop.save()
			return sum([t.score for t in Popularity.objects.filter(track=track)])

	def state(self, user, track):
		"Returns either -1 == hate, or 1 == love."
		trackpop = self.__get(user, track)
		if trackpop: return trackpop.score

	def __get(self, user, track):
		"Returns a popularity for a track. Creates a new pop object if none exists."
		try: 
			trackpop = Popularity.objects.get(track=track, user=user)
		except:
			 trackpop = Popularity(user=user, track=track)
		return trackpop

class Popularity(models.Model):
	"""Likability scheme to use for slope one predictors."""
	user = models.ForeignKey(User, related_name='voted_tracks')
	track = models.ForeignKey(Track, related_name='predictions')
	score = models.IntegerField(default=0)

	objects = models.Manager()
	popper = PopularityManager()

	class Meta:
		unique_together = (("user", "track"),)

	def love(self):
		"""Loves and saves a track."""
		self.score = 1
		self.save()

	def hate(self):
		"""Loves and saves a track."""
		self.score = -1
		self.save()

code/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>The Gossip. {%block title%}{%endblock%}</title>
	<link rel="stylesheet" href="{{MEDIA_URL}}css/reset.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="{{MEDIA_URL}}css/zoid.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="{{MEDIA_URL}}css/ui.tabs.css" type="text/css" media="screen" />
	<script type="text/javascript" src="{{MEDIA_URL}}jquery-1.2.4b.js"></script>
	<script type="text/javascript" src="{{MEDIA_URL}}ui.core.js"></script>
	<script type="text/javascript" src="{{MEDIA_URL}}ui.tabs.js"></script>
	<script type="text/javascript" src="{{MEDIA_URL}}ui.sortable.js"></script>
	<script type="text/javascript" src="{{MEDIA_URL}}zoid.js"></script>
	<script type="text/javascript" src="{{MEDIA_URL}}ui.accordion.js"></script>
	<script type="text/javascript">
	</script>
	{%block header%}{%endblock%}
</head>
<body class="{%block pageclass%}{%endblock%}">
	<div id="logo">
		<h1>The Gossip.</h1>
	</div>
	<div id="big-container">
		<div id="container">
			<ul class="ui-tabs-nav">
				<li id="music-nav"><a href="/music/"><span>Music</span></a></li>
				<li id="blogs-nav"><a href="/blogs/"><span>Blogs</span></a></li>
				{% if user.is_authenticated %}
				<li id="prefs-nav"><a href="/prefs/"><span>Preferences</span></a></li>
				{% endif %}
				{% if user.is_superuser %}
				<li id="admin-nav"><a href="/admin/"><span>Administration</span></a></li>
				{% endif %}
			</ul>
			<div class="ui-tabs-panel">
				{%block content%}{%endblock%}
			</div>

		</div>
		<div id="sidebar">
			<div class="box">
				{% if user.is_authenticated %}
				<h4>Welcome, {{user.username}} (<a href="/prefs/logout">Log out</a>)</h4>
				{% else %}
				<h4><a href="/prefs/login">Register</a>, or <a href="/prefs/login">log in!</a></h4>
				{%endif%}
			</div>
			
			<div id="more" class="box" style="display: none;">
			<h4>Generally more info
			</h4>
			<p></p>
			</div>
		</div>
	</div>
	<br /><br />
</body>
</html>

code/templates/blogs_details.html
{% if blog %}
<script language="javascript">
$(document).ready(function(){
	$("#blogsinfo").accordion( {autoHeight: false });
});
</script>
	<h4>{{blog.title}}</h4>
	<div>
		<p><a href="{{blog.url}}" id="feed_url">{{blog.url}}</a></p>
		<p>Posts: {{blog.num_posts}}</p>
		<p>Tracks: {{blog.num_tracks}}</p>
		<p>Rank: {{blog.page_rank}}</p>
	</div>
	<ul id="blogsinfo">

		{% if blog.num_posts %}
		<li id="popular">
			<a href="#" class="head">Popular artists</a>
			<ul>
			{%for artist in blog.common_artists%}
				{{artist}} .
			{%endfor%}
			</ul>
		</li>
		{% endif %}


		{% if blog.incoming %}
		<li id="ingoing">
			<a href="#" class="head">Inbound links</a>
			<ul>
			{%for link in blog.incoming%}
				<li><a href="{{link.url}}">{{link.title}}</a></li>
			{%endfor%}
			</ul>
		</li>
		{% endif %}
		
	{% if blog.outgoing %}
	<li id="outgoing">
		<a href="#" class="head">Outgoing links</a>
		<ul>
		{%for link in blog.outgoing%}
		<li><a href="{{link.url}}">{{link.title}}</a></li>
		{%endfor%}
		</ul>
	</li>
	{%endif%}
	</ul>
{% endif %}

code/templates/blogs_index.html
{% extends "base.html" %}

{%block pageclass%}blogs{%endblock%}

{%block header%}
<script type="text/javascript">
t = null;
  $(document).ready(function(){
	$("#searchbox").keyup(function(){
		value = $(this).val();
		if (t == null)
		{
			t = setTimeout(function(){
						$('#results').load("/blogs/list/?q=" + value);
						t = null;
					}, 500);
		}
	});
$('#results').load("/blogs/list/");	
});

</script>
{%endblock%}

{%block content%}
<div style="overflow: hidden; max-height: 300px">
<div class="itunesbox" style="display: none; max-height: 300px; overflow: hidden"></div>
</div>
<div class="toolbox" style="margin-top: 4px">
<div id="slidebox" style="">
	<div id="updownslides" style="float: left; width: 50px; cursor: pointer;">
		<span id="up">up</span>/<span id="down">down</span>
	</div>
</div>
<label for="searchbox">Search: </label>
<input type="text" id="searchbox" name="searchbox"/>
</div>
<div id="results">
	<div class="loading"></div>
</div>
{%endblock%}

code/templates/blogs_list.html
<script type="text/javascript" charset="utf-8">
$(document).ready(function(){
	
	// Makes the items in the list dragable
	$(".rank-list").sortable({'containment': 'parent', 'opacity': 0.8, 'axis': 'y', 'handle': '.dragarea'});
	
	// Binds so that we load extra meta data
	$(".feedlink").click(function(event) {
		event.preventDefault(); 
		$('#sidebar #more').load(event.target.href, function(){$('#sidebar #more').slideDown(300)}).slideUp(300); 
	});
	

	$(".refresh").click(function(event){
		event.preventDefault();
 x  = $(event.target).parent().parent().parent().children().filter(".data").children().filter("h4").children().filter("span")
		x.fadeOut(150);
		x.load(event.target.href, {}, function(ev){x.fadeIn(150)});
	});
		
	$(".rankable h4 a").click(function(event){
		event.preventDefault();
		$("#slidebox").animate({'height': '0', 'padding': '0'},300);
		$(".itunesbox").animate({'height': '15px'},300).html('').addClass('loading').load( event.target.href,{},function(){
			$("#slidebox").animate({'height': '10', 'padding': '5px'},300);
			$(".itunesbox").removeClass('loading').animate({'height': '207px'},300);
			});
	})
	
	// Rebinds the bottom paginator so to load dynamically.
	$("#blog-pagination > a").click(function(event) {
		event.preventDefault();
		$(this).parent().parent().load(event.target.href);
	})
	
});
</script>
{% if blog_page %}
	<ul class="rank-list" id="blogs">
	{% for blog in blog_page.object_list %}
		<li id="{{blog.id}}" class="rankable {% cycle 'odd' 'even' %}">
			<div class="data"><h4><a href="/feeds/{{blog.feed.id}}">{{blog.title}}</a> <span class="num_posts">{{blog.num_posts}} posts</span></h4>
				Feed URL: <a href="/blogs/{{blog.id}}" class="feedlink" title="{{blog.title}}">{{blog.feed.url}}</a>
			</div>
			<ul class="operations">
				<li>Operations: </li>
				<li class="dragarea">Move</li>
				<li class="traversable"><a href="/blogs/{{blog.id}}/refresh/" class="refresh">Refresh</a></li>
			</ul>
		</li>
	{% endfor %}
	</ul>
{%if draw_pagin%}
<div id="blog-pagination" class="pagination">
	{% for index in index_list %}
		{% ifnotequal index current_index %}
			<a href="/blogs/list/{{index}}?q={{query_param}}">{{index}}</a>
		{%else%}
			<div class="selected">{{index}}</div>
		{%endifnotequal%}
		{%if not forloop.last%}|{%endif%}
	{%endfor %}
</div>
{%endif%}
{% else %}
	<p>Empty blog list.</p>
{% endif %}

code/templates/feeds_list.html
{%if feed %}
<script language="text/javascript">
	my_{{feed.id}}_left=0;
$(window).ready(function(){
	wrapper = $("#feed{{feed.id}} div.wrapper");
	$('#sidebar #more').load('/blogs/{{feed.blog.id}}', function(){$('#sidebar #more').slideDown(300)}).slideUp(300); 
	$('#feed{{feed.id}} #tbleft').click(function(event){
		if (my_{{feed.id}}_left > 1)
		{
			my_{{feed.id}}_left -= 659;
			wrapper.animate({top: "0"},50);
			wrapper.animate({ 
			        left: "+=659px",
			      }, 300, 'linear' );
			
		}
	});
	$('#feed{{feed.id}} #tbright').click(function(event){
		if (my_{{feed.id}}_left < 659*({{posts|length}}-1))
		{
			my_{{feed.id}}_left += 659;
			wrapper.animate({top: "0"},50);
			wrapper.animate({ 
			        left: "-=659px",
							top: "0"
			      }, 300, 'linear' );
			
		}
	});
	
	
	$("#updownslides #down").click(function(){
		wrapper.animate({ 
		        top: "-=10px"
		      }, 50, 'linear' );
	});
	
	$("#updownslides #up").click(function(){
		wrapper.animate({ 
		        top: "+=10px"
		      }, 50, 'linear' );
	});
	
});
</script>
<div class="feed-list" id="feed{{feed.id}}">
<h4>{{feed.title}}</h4>
<a href="{{feed.url}}">{{feed.url}}</a>

<div id="toolbar">
	<span id="tbleft">&lt;</span>
	<span id="tbright">&gt;</span>
</div>
<div style="overflow: hidden; width: 1000000px">
<div class="wrapper">
{% for post in posts %}
<div class="feed-post">
	<h5>{{post.published|date:"md"}} <a href="{{post.url}}">{{post.title}}</a></h5>
	<ul>
		{% for enclosure in post.enclosures %}
		<li class="{% cycle 'odd' 'even' %}"><a href="/music/explore/{{enclosure.track.artist.id}}">{{enclosure.track.artist.name}}</a> - <a href="/music/track/{{enclosure.track.id}}">{{enclosure.track.title}}</a></li>
		{% endfor %}
	</ul>
</div>
{% endfor %}
</div>
</div>
{% endif %}

code/templates/music_artist.html
{% extends "base.html" %}

{%block pageclass%}music{%endblock%}
{% load comments %}
{%block header%}
<script type="text/javascript">
$(document).ready(function(){
	$('#similars').load('/music/similar/{{object.id}}', {}, 
	 function() { $('#similars').removeClass('loading') }).addClass('loading')
})
</script>
{%endblock%}

{%block content%}
<div id="artistinfo" class="infoblock">
	<h4>{{object.name}}</h4>
	<div id="float_wrap">
		<div id="recent_wrap">
			<h5>Recent music</h5>
			<ul>
				{% for track in object.track_set.all %}
				<li class="{% cycle 'even' 'odd' %}"><a href="/music/track/{{track.id}}">{{track.title}}</a></li>
				{% endfor %}
			</ul>
		</div>
		<div id="similar_wrap">
			<h5>Similar artists</h5>
			<div id="similars"></div>
		</div>
	</div>
	<div id="comments">
		<h5>Comments</h5>
		{% get_comment_list for music.artist object.id as comment_list %}
		{% for comment in comment_list %}
			<div class="comment {% cycle 'even' 'odd' %}">
				<a name="c{{ comment.id }}" />
				<h6>{{comment.user}}, posted {{comment.submit_date}}</h6>
				<p class="details">{{comment.comment}}</p>
			</div>
		{% endfor %}

	{% if user.is_authenticated %}
	<h5>Add a comment</h5>
		{% comment_form for music.artist object.id%}
	{% endif %}
	</div>
</div>
{%endblock%}

code/templates/music_index.html
{% extends "base.html" %}

{%block pageclass%}music{%endblock%}

{%block header%}
<script type="text/javascript">
$(document).ready(function(){

	$(".tools a").click(function(event) {
		event.preventDefault(); 
		$(event.target).parents().filter('.tools').children().removeClass('relselect');
		$(event.target).addClass('relselect');
		jQuery.get(event.target.href);
	})
})
</script>
<style type="text/css">

</style>
{%endblock%}

{%block content%}
{% ifequal pageno 1 %}
<div id="welcome">
	<h4>Your music. Now.</h4>
	<p><em>The Gossip</em> brings you the lastest in music, tailored to your ears and listening
		demands, from the hottest blogs on the internet.</p>
</div>
{% endifequal %}
{% if tracks %}
<div id="playlist">
	{% for track in tracks.object_list %}
	<div>
		
		<div class="tools">
			{% if user.is_authenticated %}
				{% ifequal track.user_relation 1 %}
				<a href="/music/love/{{track.id}}" class="love relselect">Love</a>
				{%else%}
				<a href="/music/love/{{track.id}}" class="love">Love</a> 
				{% endifequal %}
				
				{% ifequal track.user_relation -1 %}
				<a href="/music/hate/{{track.id}}" class="hate relselect">Hate</a>
				{%else%}
				<a href="/music/hate/{{track.id}}" class="hate">Hate</a>
				{% endifequal %}
			{%endif%}
	</div>
		<div class="trackinfo">
		<h4><a href="/music/explore/{{track.artist.id}}">{{track.artist.name}}</a> - 
			<a href="/music/track/{{track.id}}">{{track.title}} ({{track.trackstatistics.sort_score|floatformat}})</a></h4>
		<p><strong>Posted on:</strong>
			{% for encl in track.enclosure_set.all %} {{encl.post.feed.blog.title}} ({{encl.post.published|date:"d M Y"}}){%if not forloop.last%}, {%endif%} {%endfor%} 
		</div>
	</div>
	{% endfor %}

	<div id="blog-pagination" class="pagination" style="padding: 4px; margin-left: 55px; margin-bottom: 20px">
		{% for index in index_list %}
			{% ifnotequal index page_no %}
				<a href="/music/{{index}}">{{index}}</a>
			{%else%}
				<div class="selected">{{index}}</div>
			{%endifnotequal%}
			{%if not forloop.last%}|{%endif%}
		{%endfor %}
	</div>
</div>
{% endif %}
{%endblock%}

code/templates/music_similar.html
{%if similar%}
	<ul>
	{%for artist in similar%}
	<li class="{%cycle 'even' 'odd'%}"><a href="/music/explore/{{artist.id}}">{{artist.name}}</a></li>
	{%endfor%}
	</ul>
{%endif%}

code/templates/music_track.html
{% extends "base.html" %}

{%block pageclass%}music{%endblock%}
{% load comments %}
{%block header%}
{%endblock%}

{%block content%}
<div id="artistinfo" class="infoblock">
	<h4><a href="/music/explore/{{object.artist.id}}">{{object.artist.name}}</a> - {{object.title}}</h4>
		<div id="recent_wrap">
			<h5>Posted on</h5>
			<ul>
				{% for enclosure in object.enclosure_set.all %}
				<li class="{% cycle 'even' 'odd' %} blogpost">
					<a href="{{enclosure.post.url}}">{{enclosure.post.title}}</a> in 
					 {{enclosure.post.feed.blog.title}} 
					<a href="{{enclosure.url}}" class="download">(download)</a></li>
				{% endfor %}
			</ul>
		</div>
	<div id="comments">
		<h5>Comments</h5>
		{% get_comment_count for music.track object.id as comment_count %}
		{% get_comment_list for music.track object.id as comment_list %}
		{% ifequal comment_count 0 %}
			No comments yet. Be the first!
		{% else %}
		{% for comment in comment_list %}
			<div class="comment {% cycle 'even' 'odd' %}">
				<a name="c{{ comment.id }}" />
				<h6>{{comment.user}}, posted {{comment.submit_date}}</h6>
				<p class="details">{{comment.comment}}</p>
			</div>
		{% endfor %}
		{% endifequal %}

	{% if user.is_authenticated %}
	<h5>Add a comment</h5>
		{% comment_form for music.track object.id%}
	{% endif %}
	</div>
</div>
{%endblock%}

code/templates/prefs_login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>The Gossip - Login</title>
	<link rel="stylesheet" href="{{MEDIA_URL}}css/reset.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="{{MEDIA_URL}}css/zoid.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="{{MEDIA_URL}}css/ui.tabs.css" type="text/css" media="screen" />
	<script type="text/javascript" src="{{MEDIA_URL}}jquery-1.2.4b.js"></script>
	<script type="text/javascript" src="{{MEDIA_URL}}ui.core.js"></script>
	<script type="text/javascript" src="{{MEDIA_URL}}ui.tabs.js"></script>
	<script type="text/javascript" src="{{MEDIA_URL}}ui.sortable.js"></script>
	<script type="text/javascript" src="{{MEDIA_URL}}zoid.js"></script>
	<script type="text/javascript" src="{{MEDIA_URL}}ui.accordion.js"></script>
	<style type="text/css" media="screen">
	body {  }
		#box-wrap { top: 40%; 
								display: table-cell; vertical-align: middle;
								position: absolute;
								left: 50%;
							}
		#login-box {background: #fff; width: 300px; margin: 0 auto;
						border: 6px solid #124527; padding: 16px;
						font-size: 10pt; font-family: Lucida Grande; position: relative; top: -50%; left: -50%;}
		#login-box label { width: 90px;  padding-top: 2px; padding-right: 12px; }
		#login-box input { width: 210px; height: 18px;  margin-top: 12px; font-size: 12pt;}
		#login-box input.btn { width: 60px; height: 25px; font-size: 12pt;}
	</style>
</head>
<body>
	<div id="logo">
		<h1>The Gossip.</h1>
	</div>
	<div id="big-container">
		<div id="padding">
			<div id="box-wrap">
			<div id="login-box">
				{% if user.is_autenticated %}
				<h4>Welcome, {{user.username}}</h4>
				{% else %}
				
				{% if form.has_errors %}
				<p>Your username and password didn't match. Please try again.</p>
				{% endif %}
				
				<form method="post" action=".">
					<table>
						<tr>
							<td>
				<label for="id_username">User</label></td><td>{{ form.username }}
				</td>
					<tr><td>
				<label for="id_password">Password</label></td><td>{{ form.password }}
					</td>
					</tr>
					<tr>
						<td></td><td>
				<input type="submit" value="login" class="btn" />
				<input type="hidden" name="next" value="{{ next }}" /></td>
				</table>
				</form>
				{%endif%}
				</div>
				</div>
			</div>
		</div>
</body>
</html>

code/templates/register.html
{% extends "base.html" %}
{% block pageclass %}prefs{%endblock%}
{% block content %}
<h4>Register</h4>
{% if created %}
Account created succesfully! Get <a href="/prefs/login">surfing!</a>
{% else %}
{% if form.has_errors %}
<h2>Please correct the following error{{ form.error_dict|pluralize }}:</h2>
{% endif %}

<form method="post" action=".">
<p>
    <label for="id_name">Userame:</label> {{ form.username }}
    {% if form.username.errors %}*** {{ form.username.errors|join:", " }}{% endif %}
</p>
<p>
    <label for="id_address">E-mail:</label> {{ form.email }}
    {% if form.email.errors %}*** {{ form.email.errors|join:", " }}{% endif %}
</p>
<p>
    <label for="id_city">Passsword:</label> {{ form.password1 }}
    {% if form.password1.errors %}*** {{ form.password1.errors|join:", " }}{% endif %}
</p>
<p>
    <label for="id_city">Confirm password:</label> {{ form.password2 }}
    {% if form.password2.errors %}*** {{ form.password2.errors|join:", " }}{% endif %}
</p>
<input type="submit" />
</form>
{% endif %}
{% endblock %}